# Generated by Django 2.2 on 2019-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemaseries',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='available_series',
            field=models.ManyToManyField(to='customer.Series'),
        ),
    ]
