# Generated by Django 2.2 on 2019-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190703_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='financeAdmin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='orderAdmin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sellAdmin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouseAdmin_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
