# Generated by Django 2.2 on 2019-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190704_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
