# Generated by Django 2.2 on 2019-05-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='melody',
            name='melody_code',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='productseries',
            name='product_code',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
    ]
