# Generated by Django 2.2 on 2019-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190706_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='count',
            new_name='order_admin_verified_count',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='ordered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='sell_admin_verified_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='warehouse_admin_verified_count',
            field=models.IntegerField(default=0),
        ),
    ]
