# Generated by Django 2.2 on 2019-07-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190708_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administration_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.Order'),
        ),
    ]
