# Generated by Django 2.2 on 2019-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190708_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='warehouse_admin_verified_count',
        ),
    ]
