# Generated by Django 2.2 on 2019-07-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_shopitem_warehouse_admin_verified_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
