# Generated by Django 2.2 on 2019-09-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_promotions_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='answer',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='schemaseries',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
