# Generated by Django 2.2 on 2019-09-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20190920_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='count',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='price',
        ),
    ]
