# Generated by Django 2.2 on 2019-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190922_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(default='', max_length=128),
        ),
    ]
