# Generated by Django 2.2 on 2019-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='administration_process',
        ),
        migrations.RemoveField(
            model_name='order',
            name='financeAdmin_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderAdmin_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sellAdmin_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warehouseAdmin_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(-1, 'created'), (0, 'checked_out'), (1, 'confirmed'), (2, 'orderAdmin_confirmed'), (3, 'sellAdmin_confirmed'), (4, 'warehouseAdmin_confirmed'), (5, 'financeAdmin_confirmed'), (6, 'administration_process')], default=-1, max_length=128),
        ),
    ]
