# Generated by Django 2.2 on 2020-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20191129_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='operator_name',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(db_index=True, max_length=86),
        ),
    ]
