# Generated by Django 2.2 on 2020-05-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20200508_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administration_comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='financeAdmin_comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='orderAdmin_comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='sellAdmin_comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouseAdmin_comment',
            field=models.CharField(default='', max_length=256),
        ),
    ]
