# Generated by Django 2.2 on 2020-05-08 09:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20200508_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='melody',
            name='picture',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images'), upload_to=''),
        ),
    ]
